using System;

namespace BO2_Console_V4.Info
{
	// Token: 0x02000052 RID: 82
	public static class BuiltInCFGs
	{
		// Token: 0x040002C2 RID: 706
		public static string Default = "cg_draw2d \"1\";cg_chatHeight \"0\";cg_drawCrosshair \"1\";cg_drawGun \"1\";cg_fov \"90\";cg_fovscale \"1\";cg_gun_x \"0\";cg_gun_y \"0\";cg_gun_z \"0\";cg_overheadIconSize \"0\";cg_overheadNamesSize \"0\";cg_overheadRankSize \"0\";cg_centertime \"0\";cg_useColorControl \"0\";cg_colorTemp \"360\";cg_colorScale \"1 1 1\";con_gameMsgWindow0LineCount \"4\";con_gameMsgWindow0MsgTime \"5\";g_TeamColor_Axis \"0.65 0.57 0.41 1\";g_TeamColor_Allies \"0.52 0.28 0.28 1\";phys_gravity \"-800\";r_exposureTweak \"0\";r_exposureValue \"12.5\";r_skytransition \"0\";r_heroLightScale \"1 1 1\";r_modellimit \"1024\";r_dobjLimit \"512\";r_skipPvs \"0\";r_lockPvs \"0\";r_clearColor \"0 0 0 0\";r_clearColor2 \"0 0 0 0\";r_bloomTweaks \"0\";r_bloomHiQuality \"1\";r_skyColorTemp \"6500\";r_sky_intensity_factor0 \"1\";r_sky_intensity_factor1 \"1\";r_lightTweakSunColor \"0.8 0.75 0.7\";r_lightTweakSunLight \"15\";r_ssao \"3_HBAO\";r_ssaoScale \"50\";r_ssaoRadius \"12\";r_ssaoBias \"0.55\";r_ssaoIntensity \"0.53\";r_aaalpha \"2\";r_aasamples \"16\";r_texFilterMipMode \"Force Trilinear\";r_texFilterAnisoMin \"16\";r_texFilterAnisoMax \"16\";r_autoLodScale \"0\";r_lodBiasRigid \"-1000\";r_lodBiasSkinned \"-1000\";r_lodScaleRigid \"1\";r_lodScaleSkinned \"1\";r_dofHDR \"2\";r_dof_bias \"0.5\";r_dof_enable \"1\";r_dof_farBlur \"1.8\";r_dof_farEnd \"7000\";r_dof_farStart \"1000\";r_dof_nearBlur \"0\";r_dof_nearEnd \"0\";r_dof_nearStart \"0\";r_dof_tweak \"0\";r_znear \"4\";r_zfar \"0\";r_fxaa \"0\";phys_gravity \"-800\";waypointIconWidth \"0\";waypointIconHeight \"0\";waypointOffscreenPointerHeight \"0\";waypointOffscreenPointerWidth \"0\";hud_health_pulserate_critical \"0\";hud_health_pulserate_injured \"0\";hud_health_startpulse_critical \"0\";hud_health_startpulse_injured \"0\";hud_healthOverlay_phaseEnd_pulseDuration \"0\";hud_healthOverlay_phaseEnd_toAlpha \"0\";hud_healthOverlay_phaseOne_pulseDuration \"0\";hud_healthOverlay_phaseOne_toAlphaAdd \"0\";hud_healthOverlay_phaseThree_pulseDuration \"0\";hud_healthOverlay_phaseThree_toAlphaMultiplier \"0\";hud_healthOverlay_phaseTwo_pulseDuration \"0\";hud_healthOverlay_phaseTwo_toAlphaMultiplier \"0\";hud_healthOverlay_pulseStart \"0\";hud_healthOverlay_regenPauseTime \"0\";timescale \"1\";";
	}
}
